name: Copilot-user-activity

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
  # schedule:
  #   # Runs at the beginning of every hour
  #   - cron: '0 * * * *'

jobs:
  Copilot-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v4
   
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"

    - name: Install python dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Copilot User list 
      run: |
          python copilot.py
      env:
          GH_ADMIN_TOKEN: ${{ secrets.REPORTS_PAT }}

    - name: Github Copilot report
      uses: actions/upload-artifact@v4
      with:
        name: Copilot_Users${{ steps.date.outputs.date }}
        path: |
          ${{ github.workspace }}/*.csv
          ${{ github.workspace }}/*.log
