name: Run Copilot Metrics Script

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs at the beginning of every hour

jobs:
  copilot-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"

    - name: Install python dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Copilot Metrics Script
      run: |
          python copilot-metrics.py
      env:
          ENTERPRISE_ID: ${{ secrets.ENTERPRISE_ID }}
          ENTERPRISE_SLUG: ${{ secrets.ENTERPRISE_SLUG }}
          GITHUB_TOKEN: ${{ secrets.REPORTS_PAT }}

    - name: Upload Copilot Metrics Report
      uses: actions/upload-artifact@v3
      with:
        name: Copilot_Metrics_Report
        path: |
          ./*.csv
          ./*.log
